version: '2'

services:
    tcgplace-cards-db:
      image: mysql:5.7
      container_name: tcgplace_db
      restart: always
      volumes:
      - data:/var/lib/mysql    
      - ./db/scripts:/docker-entrypoint-initdb.d
      ports:
      - "3306:3306"
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: tcgplace           
    tcgplace-cards-service:
        image: java:openjdk-8u91-jdk
        container_name: tcgplace_app
        working_dir: /app
        volumes:
        - ./build/libs:/app
        command: java -jar /app/tcgplace.cards-1.0.0.jar
        ports:
        - "8080:8080"
        depends_on:
        - tcgplace-cards-db        
        links:
        - tcgplace-cards-db
volumes:
    data:      
